#ifndef TYPE_SYSTEM_TYPE_OPERATORS_H
#define TYPE_SYSTEM_TYPE_OPERATORS_H

typedef enum {
  PSX_TYPE_BINARY_COMMA = 0,
  PSX_TYPE_BINARY_ADD,
  PSX_TYPE_BINARY_SUB,
  PSX_TYPE_BINARY_MUL,
  PSX_TYPE_BINARY_DIV,
  PSX_TYPE_BINARY_MOD,
  PSX_TYPE_BINARY_BITAND,
  PSX_TYPE_BINARY_BITXOR,
  PSX_TYPE_BINARY_BITOR,
  PSX_TYPE_BINARY_SHL,
  PSX_TYPE_BINARY_SHR,
  PSX_TYPE_BINARY_COMPARE,
  PSX_TYPE_BINARY_LOGICAL,
} psx_type_binary_op_t;

typedef enum {
  PSX_TYPE_UNARY_NEGATE = 0,
  PSX_TYPE_UNARY_REAL,
  PSX_TYPE_UNARY_IMAGINARY,
} psx_type_arithmetic_unary_op_t;

#endif
