#ifndef SEMANTIC_TYPED_HIR_BUILD_STATUS_H
#define SEMANTIC_TYPED_HIR_BUILD_STATUS_H

typedef struct token_t token_t;

typedef enum {
  PSX_RESOLVED_HIR_BUILD_OK = 0,
  PSX_RESOLVED_HIR_BUILD_INVALID_INPUT,
  PSX_RESOLVED_HIR_BUILD_UNFINALIZED_RESOLUTION,
  PSX_RESOLVED_HIR_BUILD_UNMATERIALIZED,
  PSX_RESOLVED_HIR_BUILD_RAW_SYNTAX_REMAINS,
  PSX_RESOLVED_HIR_BUILD_MISSING_CANONICAL_TYPE,
  PSX_RESOLVED_HIR_BUILD_MISSING_RESOLVED_SYMBOL,
  PSX_RESOLVED_HIR_BUILD_OUT_OF_MEMORY,
} psx_resolved_hir_build_status_t;

typedef enum {
  PSX_SYNTAX_TYPED_HIR_REJECTION_NONE = 0,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DUPLICATE_LABEL,
  PSX_SYNTAX_TYPED_HIR_REJECTION_UNDEFINED_GOTO,
  PSX_SYNTAX_TYPED_HIR_REJECTION_BREAK_OUTSIDE_LOOP_OR_SWITCH,
  PSX_SYNTAX_TYPED_HIR_REJECTION_CONTINUE_OUTSIDE_LOOP,
  PSX_SYNTAX_TYPED_HIR_REJECTION_CASE_OUTSIDE_SWITCH,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DEFAULT_OUTSIDE_SWITCH,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DUPLICATE_CASE,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DUPLICATE_DEFAULT,
  PSX_SYNTAX_TYPED_HIR_REJECTION_RETURN_VALUE_REQUIRED,
  PSX_SYNTAX_TYPED_HIR_REJECTION_RETURN_VALUE_FORBIDDEN,
  PSX_SYNTAX_TYPED_HIR_REJECTION_STATIC_ASSERT_NOT_CONSTANT,
  PSX_SYNTAX_TYPED_HIR_REJECTION_STATIC_ASSERT_FAILED,
  PSX_SYNTAX_TYPED_HIR_REJECTION_CASE_NOT_INTEGER_CONSTANT,
  PSX_SYNTAX_TYPED_HIR_REJECTION_UNDEFINED_IDENTIFIER,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DOT_BASE_NOT_AGGREGATE,
  PSX_SYNTAX_TYPED_HIR_REJECTION_ARROW_BASE_NOT_AGGREGATE_POINTER,
  PSX_SYNTAX_TYPED_HIR_REJECTION_MEMBER_NOT_FOUND,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DEREF_REQUIRES_POINTER,
  PSX_SYNTAX_TYPED_HIR_REJECTION_DEREF_VOID_POINTER,
} psx_syntax_typed_hir_rejection_t;

typedef struct psx_resolved_hir_build_failure_t {
  psx_resolved_hir_build_status_t status;
  psx_syntax_typed_hir_rejection_t rejection;
  int source_node_kind;
  const token_t *source_token;
  const char *source_name;
  int source_name_length;
  long long source_integer_value;
} psx_resolved_hir_build_failure_t;

#endif
