#include "tokenizer.h"
#include <string.h>

/** @brief token kind を表示用文字列へ変換する。 */
const char *tk_token_kind_str(token_kind_t kind, int *len) {
  const char *s = NULL;
  switch (kind) {
    case TK_IF: s = "if"; break;
    case TK_ELSE: s = "else"; break;
    case TK_WHILE: s = "while"; break;
    case TK_FOR: s = "for"; break;
    case TK_RETURN: s = "return"; break;
    case TK_AUTO: s = "auto"; break;
    case TK_BREAK: s = "break"; break;
    case TK_CASE: s = "case"; break;
    case TK_CONST: s = "const"; break;
    case TK_CONTINUE: s = "continue"; break;
    case TK_DEFAULT: s = "default"; break;
    case TK_DO: s = "do"; break;
    case TK_ENUM: s = "enum"; break;
    case TK_EXTERN: s = "extern"; break;
    case TK_GOTO: s = "goto"; break;
    case TK_INLINE: s = "inline"; break;
    case TK_INT: s = "int"; break;
    case TK_REGISTER: s = "register"; break;
    case TK_RESTRICT: s = "restrict"; break;
    case TK_SIGNED: s = "signed"; break;
    case TK_SIZEOF: s = "sizeof"; break;
    case TK_STATIC: s = "static"; break;
    case TK_STRUCT: s = "struct"; break;
    case TK_SWITCH: s = "switch"; break;
    case TK_TYPEDEF: s = "typedef"; break;
    case TK_UNION: s = "union"; break;
    case TK_UNSIGNED: s = "unsigned"; break;
    case TK_VOLATILE: s = "volatile"; break;
    case TK_CHAR: s = "char"; break;
    case TK_VOID: s = "void"; break;
    case TK_SHORT: s = "short"; break;
    case TK_LONG: s = "long"; break;
    case TK_FLOAT: s = "float"; break;
    case TK_DOUBLE: s = "double"; break;
    case TK_ALIGNAS: s = "_Alignas"; break;
    case TK_ALIGNOF: s = "_Alignof"; break;
    case TK_ATOMIC: s = "_Atomic"; break;
    case TK_BOOL: s = "_Bool"; break;
    case TK_COMPLEX: s = "_Complex"; break;
    case TK_GENERIC: s = "_Generic"; break;
    case TK_IMAGINARY: s = "_Imaginary"; break;
    case TK_NORETURN: s = "_Noreturn"; break;
    case TK_STATIC_ASSERT: s = "_Static_assert"; break;
    case TK_THREAD_LOCAL: s = "_Thread_local"; break;
    case TK_LPAREN: s = "("; break;
    case TK_RPAREN: s = ")"; break;
    case TK_LBRACE: s = "{"; break;
    case TK_RBRACE: s = "}"; break;
    case TK_LBRACKET: s = "["; break;
    case TK_RBRACKET: s = "]"; break;
    case TK_COMMA: s = ","; break;
    case TK_SEMI: s = ";"; break;
    case TK_ASSIGN: s = "="; break;
    case TK_PLUS: s = "+"; break;
    case TK_MINUS: s = "-"; break;
    case TK_MUL: s = "*"; break;
    case TK_DIV: s = "/"; break;
    case TK_MOD: s = "%"; break;
    case TK_BANG: s = "!"; break;
    case TK_TILDE: s = "~"; break;
    case TK_LT: s = "<"; break;
    case TK_LE: s = "<="; break;
    case TK_GT: s = ">"; break;
    case TK_GE: s = ">="; break;
    case TK_EQEQ: s = "=="; break;
    case TK_NEQ: s = "!="; break;
    case TK_ANDAND: s = "&&"; break;
    case TK_OROR: s = "||"; break;
    case TK_AMP: s = "&"; break;
    case TK_PIPE: s = "|"; break;
    case TK_CARET: s = "^"; break;
    case TK_QUESTION: s = "?"; break;
    case TK_COLON: s = ":"; break;
    case TK_INC: s = "++"; break;
    case TK_DEC: s = "--"; break;
    case TK_SHL: s = "<<"; break;
    case TK_SHR: s = ">>"; break;
    case TK_ARROW: s = "->"; break;
    case TK_PLUSEQ: s = "+="; break;
    case TK_MINUSEQ: s = "-="; break;
    case TK_MULEQ: s = "*="; break;
    case TK_DIVEQ: s = "/="; break;
    case TK_MODEQ: s = "%="; break;
    case TK_SHLEQ: s = "<<="; break;
    case TK_SHREQ: s = ">>="; break;
    case TK_ANDEQ: s = "&="; break;
    case TK_XOREQ: s = "^="; break;
    case TK_OREQ: s = "|="; break;
    case TK_ELLIPSIS: s = "..."; break;
    case TK_HASH: s = "#"; break;
    case TK_HASHHASH: s = "##"; break;
    case TK_DOT: s = "."; break;
    case TK_EOF: s = "EOF"; break;
    default: s = NULL; break;
  }
  if (len) *len = s ? (int)strlen(s) : 0;
  return s;
}
