export interface AgcWasmCompilerOptions {
  sourcePtr?: number;
  sourceCap?: number;
  outputPtr?: number;
  outputCap?: number;
  initialOutputCap?: number;
  useHeapBuffers?: boolean;
  onStdout?: (chunk: string) => void;
  onStderr?: (chunk: string) => void;
  onExit?: (status: number) => void;
  onAbort?: (status: number) => void;
  onTerminate?: (event: AgcWasmTerminationEvent) => void;
  limits?: Partial<AgcResourceLimits>;
}

export interface AgcResourceLimits {
  maxSources: number;
  maxSourceBytes: number;
  maxTotalSourceBytes: number;
  maxHeaders: number;
  maxHeaderBytes: number;
  maxTotalHeaderBytes: number;
  maxIncludeDepth: number;
  maxObjectBytes: number;
  maxLinkedWasmBytes: number;
  maxDiagnostics: number;
  maxDiagnosticBytes: number;
  maxAnalysisSymbols: number;
  maxCompletionItems: number;
  maxAnalysisStringBytes: number;
  maxAnalysisSnapshotBytes: number;
}

export type AgcResourceLimitCode =
  | "AGC_LIMIT_MAX_SOURCES"
  | "AGC_LIMIT_MAX_SOURCE_BYTES"
  | "AGC_LIMIT_MAX_TOTAL_SOURCE_BYTES"
  | "AGC_LIMIT_MAX_HEADERS"
  | "AGC_LIMIT_MAX_HEADER_BYTES"
  | "AGC_LIMIT_MAX_TOTAL_HEADER_BYTES"
  | "AGC_LIMIT_MAX_INCLUDE_DEPTH"
  | "AGC_LIMIT_MAX_OBJECT_BYTES"
  | "AGC_LIMIT_MAX_LINKED_WASM_BYTES"
  | "AGC_LIMIT_MAX_DIAGNOSTICS"
  | "AGC_LIMIT_MAX_DIAGNOSTIC_BYTES"
  | "AGC_LIMIT_MAX_ANALYSIS_SYMBOLS"
  | "AGC_LIMIT_MAX_COMPLETION_ITEMS"
  | "AGC_LIMIT_MAX_ANALYSIS_STRING_BYTES"
  | "AGC_LIMIT_MAX_ANALYSIS_SNAPSHOT_BYTES";

export class AgcResourceLimitError extends RangeError {
  readonly name: "AgcResourceLimitError";
  readonly code: AgcResourceLimitCode;
  readonly limit: keyof AgcResourceLimits;
  readonly max: number;
  readonly actual: number;
  readonly diagnostics: readonly AgcDiagnostic[];
}

export interface AgcWasmTerminationEvent {
  kind: "exit" | "abort" | "unknown";
  status: number;
}

export interface AgcDiagnosticPosition {
  /** 1-based line in the normalized UTF-8 compiler input. */
  readonly line: number;
  /** 1-based UTF-8 byte column. */
  readonly column: number;
  /** 0-based UTF-8 byte offset. */
  readonly offset: number;
}

export interface AgcDiagnostic {
  readonly severity: "error" | "warning" | "note";
  readonly code: string;
  readonly message: string;
  readonly sourceId: number;
  readonly sourceName: string;
  readonly start: AgcDiagnosticPosition;
  /** Exclusive end position. */
  readonly end: AgcDiagnosticPosition;
  readonly notes: readonly AgcDiagnostic[];
}

export interface AgcWasmDiagnosticError extends Error {
  diagnostics: readonly AgcDiagnostic[];
}

export interface AgcWasmObjectResult {
  object: Uint8Array;
  diagnostics: readonly AgcDiagnostic[];
  /** Sorted canonical virtual-header names opened by this translation unit. */
  dependencies: readonly string[];
}

export interface AgcWasmWatResult {
  wat: string;
  diagnostics: readonly AgcDiagnostic[];
}

export interface AgcNamedSource {
  /** Diagnostic/debug identity only; it is never fetched or opened by the JS API. */
  name: string;
  source: string;
}

export type AgcCompileInput = string | AgcNamedSource;

export interface AgcVirtualHeaderLimits {
  maxFiles?: number;
  maxFileBytes?: number;
  maxTotalBytes?: number;
  maxIncludeDepth?: number;
}

export interface AgcCompileOptions {
  /** Locale used for diagnostics generated by this compile request. */
  diagnosticLocale?: "ja" | "en";
  /** Canonical, project-relative virtual paths mapped to UTF-8 C source. */
  headers?: Record<string, string>;
  headerLimits?: AgcVirtualHeaderLimits;
  /** Per-compile overrides of the compiler/toolchain resource policy. */
  limits?: Partial<AgcResourceLimits>;
}

export interface AgcAnalysisCursor {
  sourceName: string;
  /** 0-based byte offset in normalized UTF-8. */
  byteOffset: number;
}

export interface AgcAnalysisOptions extends AgcCompileOptions {
  cursor: AgcAnalysisCursor;
}

export interface AgcLanguageSourceRange {
  readonly sourceName: string;
  readonly start: AgcDiagnosticPosition;
  readonly end: AgcDiagnosticPosition;
}

export interface AgcLanguageInitializer {
  readonly state: "none" | "explicitConstant" | "zero" | "indeterminate" | "runtime";
  readonly constantValue: string | null;
  readonly range: AgcLanguageSourceRange | null;
}

export interface AgcLanguageFunctionInfo {
  readonly returnType: string;
  readonly hasPrototype: boolean;
  readonly variadic: boolean;
  readonly parameters: readonly {
    readonly name: string;
    readonly type: string;
  }[];
}

export interface AgcLanguageMacroInfo {
  readonly functionLike: boolean;
  readonly variadic: boolean;
  readonly parameters: readonly string[];
  readonly replacement: string;
}

export interface AgcLanguageSymbol {
  readonly name: string;
  readonly kind: "object" | "parameter" | "function" | "typedef" |
    "enumConstant" | "tag" | "member" | "macro";
  readonly nameSpace: "ordinary" | "tag" | "label" | "member" | "macro";
  readonly type: string;
  readonly signature: string;
  readonly storageClass: string;
  readonly scopeDepth: number;
  readonly declarationOrder: number;
  readonly declaration: AgcLanguageSourceRange;
  readonly initializer: AgcLanguageInitializer;
  readonly function: AgcLanguageFunctionInfo | null;
  readonly macro: AgcLanguageMacroInfo | null;
}

export interface AgcLanguageAnalysisSnapshot {
  readonly diagnostics: readonly AgcDiagnostic[];
  readonly completionItems: readonly AgcLanguageSymbol[];
  readonly hover: AgcLanguageSymbol | null;
  readonly partial: boolean;
}

export interface AgcWasmCompiler {
  instance: WebAssembly.Instance;
  memory: WebAssembly.Memory;
  limits: {
    sourcePtr: number;
    sourceCap: number;
    outputPtr: number;
    outputCap: number;
    initialOutputCap: number;
    useHeapBuffers: boolean;
  };
  resourceLimits: Readonly<AgcResourceLimits>;
  compileWat(source: AgcCompileInput, options?: AgcCompileOptions): string;
  compileWatWithDiagnostics(source: AgcCompileInput, options?: AgcCompileOptions): AgcWasmWatResult;
  compileObject(source: AgcCompileInput, options?: AgcCompileOptions): Uint8Array;
  compileObjectWithDiagnostics(
    source: AgcCompileInput,
    options?: AgcCompileOptions,
  ): AgcWasmObjectResult;
  analyzeSource(source: AgcNamedSource, options: AgcAnalysisOptions): AgcLanguageAnalysisSnapshot;
  readStdout(): string;
  readStderr(): string;
  readDiagnostics(): readonly AgcDiagnostic[];
  readDiagnosticBytes(): number;
  readTermination(): AgcWasmTerminationEvent | null;
  dispose(): void;
  diagnosticCoordinateSystem: {
    encoding: "utf-8";
    input: "normalized";
    offsetBase: 0;
    lineBase: 1;
    columnBase: 1;
    end: "exclusive";
  };
}

export type AgcWasmSource = string | URL | WebAssembly.Module | ArrayBuffer | Uint8Array;

export function createCompiler(
  wasmSource: AgcWasmSource,
  options?: AgcWasmCompilerOptions,
): Promise<AgcWasmCompiler>;

export default createCompiler;
