#ifndef DIAG_ERROR_CATALOG_H
#define DIAG_ERROR_CATALOG_H

typedef enum {
  DIAG_ERR_INTERNAL_OOM = 1,

  DIAG_ERR_PREPROCESS_GENERIC = 1000,

  DIAG_ERR_TOKENIZER_GENERIC = 2000,
  DIAG_ERR_TOKENIZER_UNEXPECTED_CHAR = 2001,
  DIAG_ERR_TOKENIZER_TOKEN_TOO_LONG = 2002,
  DIAG_ERR_TOKENIZER_UNTERMINATED = 2003,
  DIAG_ERR_TOKENIZER_INVALID_NUMBER = 2004,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE = 2005,
  DIAG_ERR_TOKENIZER_EXPECTED_TOKEN = 2006,
  DIAG_ERR_TOKENIZER_EXPECTED_INTEGER = 2007,
  DIAG_ERR_TOKENIZER_INVALID_CHAR_LITERAL = 2008,
  DIAG_ERR_TOKENIZER_UNTERMINATED_COMMENT = 2009,
  DIAG_ERR_TOKENIZER_UNTERMINATED_LITERAL = 2010,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE_HEX = 2011,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE_UCN = 2012,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE_GENERAL = 2013,

  DIAG_ERR_PARSER_GENERIC = 3000,
  DIAG_ERR_PARSER_EXPECTED_TOKEN = 3001,
  DIAG_ERR_PARSER_UNEXPECTED_TOKEN = 3002,
  DIAG_ERR_PARSER_UNDEFINED_SYMBOL = 3003,
  DIAG_ERR_PARSER_DUPLICATE_SYMBOL = 3004,
  DIAG_ERR_PARSER_INVALID_CONTEXT = 3005,
  DIAG_ERR_PARSER_INVALID_TYPE_SPEC = 3006,

  DIAG_ERR_CODEGEN_GENERIC = 4000,
  DIAG_ERR_CODEGEN_OUTPUT_FAILED = 4001,
  DIAG_ERR_CODEGEN_INVALID_LVALUE = 4002,
  DIAG_ERR_CODEGEN_INVALID_CONTROL_FLOW = 4003,
} diag_error_id_t;

/**
 * @brief エラーIDを表示用コード（例: "E3002"）へ変換する。
 * @param id エラーID。
 * @return 対応する表示用コード文字列。未定義IDの場合は既定コード。
 */
const char *diag_error_code(diag_error_id_t id);

/**
 * @brief エラーIDを論理キー（例: "parser.unexpected_token"）へ変換する。
 * @param id エラーID。
 * @return 対応する論理キー文字列。未定義IDの場合は既定キー。
 */
const char *diag_error_key(diag_error_id_t id);

#endif
