#ifndef DIAG_ERROR_CATALOG_H
#define DIAG_ERROR_CATALOG_H

typedef enum {
  DIAG_ERR_INTERNAL_OOM = 1,

  DIAG_ERR_PREPROCESS_GENERIC = 1000,

  DIAG_ERR_TOKENIZER_GENERIC = 2000,
  DIAG_ERR_TOKENIZER_UNEXPECTED_CHAR = 2001,
  DIAG_ERR_TOKENIZER_TOKEN_TOO_LONG = 2002,
  DIAG_ERR_TOKENIZER_UNTERMINATED = 2003,
  DIAG_ERR_TOKENIZER_INVALID_NUMBER = 2004,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE = 2005,
  DIAG_ERR_TOKENIZER_EXPECTED_TOKEN = 2006,
  DIAG_ERR_TOKENIZER_EXPECTED_INTEGER = 2007,
  DIAG_ERR_TOKENIZER_INVALID_CHAR_LITERAL = 2008,
  DIAG_ERR_TOKENIZER_UNTERMINATED_COMMENT = 2009,
  DIAG_ERR_TOKENIZER_UNTERMINATED_LITERAL = 2010,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE_HEX = 2011,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE_UCN = 2012,
  DIAG_ERR_TOKENIZER_INVALID_ESCAPE_GENERAL = 2013,

  DIAG_ERR_PARSER_GENERIC = 3000,
  DIAG_ERR_PARSER_EXPECTED_TOKEN = 3001,
  DIAG_ERR_PARSER_UNEXPECTED_TOKEN = 3002,
  DIAG_ERR_PARSER_UNDEFINED_SYMBOL = 3003,
  DIAG_ERR_PARSER_DUPLICATE_SYMBOL = 3004,
  DIAG_ERR_PARSER_INVALID_CONTEXT = 3005,
  DIAG_ERR_PARSER_INVALID_TYPE_SPEC = 3006,
  DIAG_ERR_PARSER_STRING_LITERAL_TOO_LARGE = 3007,
  DIAG_ERR_PARSER_STRING_CONCAT_SIZE_INVALID = 3008,
  DIAG_ERR_PARSER_STATIC_ASSERT_EXPECTED = 3009,
  DIAG_ERR_PARSER_STATIC_ASSERT_COND_NOT_CONST = 3010,
  DIAG_ERR_PARSER_STATIC_ASSERT_MSG_NOT_STRING = 3011,
  DIAG_ERR_PARSER_STATIC_ASSERT_FAILED = 3012,
  DIAG_ERR_PARSER_MISSING_FUNC_DECL_RPAREN = 3013,
  DIAG_ERR_PARSER_TYPEDEF_NAME_REQUIRED = 3014,
  DIAG_ERR_PARSER_TYPE_NAME_REQUIRED = 3015,
  DIAG_ERR_PARSER_VARIABLE_NAME_REQUIRED = 3016,
  DIAG_ERR_PARSER_ALIGNAS_LPAREN_REQUIRED = 3017,
  DIAG_ERR_PARSER_ATOMIC_TYPE_NAME_REQUIRED = 3018,
  DIAG_ERR_PARSER_ARRAY_SIZE_POSITIVE_REQUIRED = 3019,
  DIAG_ERR_PARSER_INCOMPLETE_MEMBER_FORBIDDEN = 3020,
  DIAG_ERR_PARSER_MEMBER_TYPE_REQUIRED = 3021,
  DIAG_ERR_PARSER_FUNCTION_MEMBER_FORBIDDEN = 3022,
  DIAG_ERR_PARSER_TYPEDEF_KEYWORD_REQUIRED = 3023,

  DIAG_ERR_CODEGEN_GENERIC = 4000,
  DIAG_ERR_CODEGEN_OUTPUT_FAILED = 4001,
  DIAG_ERR_CODEGEN_INVALID_LVALUE = 4002,
  DIAG_ERR_CODEGEN_INVALID_CONTROL_FLOW = 4003,
} diag_error_id_t;

/**
 * @brief エラーIDを表示用コード（例: "E3002"）へ変換する。
 * @param id エラーID。
 * @return 対応する表示用コード文字列。未定義IDの場合は既定コード。
 */
const char *diag_error_code(diag_error_id_t id);

/**
 * @brief エラーIDを論理キー（例: "parser.unexpected_token"）へ変換する。
 * @param id エラーID。
 * @return 対応する論理キー文字列。未定義IDの場合は既定キー。
 */
const char *diag_error_key(diag_error_id_t id);

#endif
