#ifndef DIAG_WARNING_CATALOG_H
#define DIAG_WARNING_CATALOG_H

typedef enum {
  DIAG_WARN_PARSER_IMPLICIT_INT_RETURN = 3001,
  DIAG_WARN_PARSER_UNREACHABLE_CODE = 3002,
  DIAG_WARN_PARSER_UNUSED_VARIABLE = 3003,
  DIAG_WARN_PARSER_UNINITIALIZED_VARIABLE = 3004,
  DIAG_WARN_PARSER_MISSING_RETURN = 3005,
  DIAG_WARN_PARSER_RETURN_STACK_ADDRESS = 3006,
  DIAG_WARN_PARSER_ASSIGN_IN_CONDITION = 3007,
  DIAG_WARN_PARSER_COMMA_IN_CONDITION = 3008,
  DIAG_WARN_PARSER_EMPTY_BODY = 3009,
  DIAG_WARN_PARSER_FLOAT_TO_INT_NARROWING = 3010,
  DIAG_WARN_PARSER_CONSTANT_OVERFLOW = 3011,
  DIAG_WARN_PARSER_SELF_ASSIGN = 3012,
  DIAG_WARN_PARSER_SELF_COMPARE = 3013,
  DIAG_WARN_PARSER_SHIFT_OUT_OF_RANGE = 3014,
  DIAG_WARN_PARSER_DIVIDE_BY_ZERO = 3015,
  DIAG_WARN_PARSER_IMPLICIT_FUNCTION_DECL = 3016,
  DIAG_WARN_PARSER_SWITCH_FALLTHROUGH = 3017,
  DIAG_WARN_PARSER_SIGN_COMPARE = 3018,
  DIAG_WARN_PARSER_TAUTOLOGICAL_UNSIGNED_ZERO = 3019,
  DIAG_WARN_PARSER_IDENTICAL_LOGICAL_OPERANDS = 3020,
  DIAG_WARN_PARSER_LOGICAL_NOT_PARENTHESES = 3021,
} diag_warn_id_t;

const char *diag_warn_code(diag_warn_id_t id);
const char *diag_warn_key(diag_warn_id_t id);

#endif
