#ifndef _INTTYPES_H
#define _INTTYPES_H
#include <stdint.h>
/* C11 7.8: 整数型の printf/scanf 書式マクロと最大幅整数の関数。
 * Apple ARM64: int32_t=int, int64_t=long long, intmax_t=long long。 */
typedef struct { intmax_t quot; intmax_t rem; } imaxdiv_t;

#define PRId8   "hhd"
#define PRId16  "hd"
#define PRId32  "d"
#define PRId64  "lld"
#define PRIdMAX "lld"
#define PRIdPTR "ld"
#define PRIi8   "hhi"
#define PRIi16  "hi"
#define PRIi32  "i"
#define PRIi64  "lli"
#define PRIiMAX "lli"
#define PRIiPTR "li"
#define PRIo8   "hho"
#define PRIo16  "ho"
#define PRIo32  "o"
#define PRIo64  "llo"
#define PRIoMAX "llo"
#define PRIoPTR "lo"
#define PRIu8   "hhu"
#define PRIu16  "hu"
#define PRIu32  "u"
#define PRIu64  "llu"
#define PRIuMAX "llu"
#define PRIuPTR "lu"
#define PRIx8   "hhx"
#define PRIx16  "hx"
#define PRIx32  "x"
#define PRIx64  "llx"
#define PRIxMAX "llx"
#define PRIxPTR "lx"
#define PRIX8   "hhX"
#define PRIX16  "hX"
#define PRIX32  "X"
#define PRIX64  "llX"
#define PRIXMAX "llX"
#define PRIXPTR "lX"

#define SCNd8   "hhd"
#define SCNd16  "hd"
#define SCNd32  "d"
#define SCNd64  "lld"
#define SCNdMAX "lld"
#define SCNdPTR "ld"
#define SCNi8   "hhi"
#define SCNi16  "hi"
#define SCNi32  "i"
#define SCNi64  "lli"
#define SCNiMAX "lli"
#define SCNiPTR "li"
#define SCNo8   "hho"
#define SCNo16  "ho"
#define SCNo32  "o"
#define SCNo64  "llo"
#define SCNoMAX "llo"
#define SCNoPTR "lo"
#define SCNu8   "hhu"
#define SCNu16  "hu"
#define SCNu32  "u"
#define SCNu64  "llu"
#define SCNuMAX "llu"
#define SCNuPTR "lu"
#define SCNx8   "hhx"
#define SCNx16  "hx"
#define SCNx32  "x"
#define SCNx64  "llx"
#define SCNxMAX "llx"
#define SCNxPTR "lx"

intmax_t imaxabs(intmax_t j);
imaxdiv_t imaxdiv(intmax_t numer, intmax_t denom);
intmax_t strtoimax(const char *nptr, char **endptr, int base);
uintmax_t strtoumax(const char *nptr, char **endptr, int base);
#endif
